@startuml
start
    :记录当前节点(此处为第一个节点即头节点指向的节点);
    :置空头节点的Ｎext;
    repeat
        :记录当前节点的下一个结点;
        :将当前节点指向头节点的下一个节点;
        :将头节点指向当前节点;
        :将当前节点后移;
    repeat while (当前节点不为空?) is (yes)
stop
@enduml