@startuml
start
    :记录当前节点(外循环)(此处为第一个节点即头节点指向的节点);
    while (外循环当前节点不为空?) is (yes)
        :将内循环前驱节点设置为外循环当前节点;
        :将内循环当前节点设置为外循环当前节点的下一个节点;
        while (内循环当前节点不为空?) is (yes)
            if (内外循环当前节点内容相等) then (yes)
                :将内循环前驱节点的下
一个节点设置为内循
环当前节点的下一个节点;
            else (no)
                :将内循环前驱节点
设置为外循环当前节点;
            endif
            :将内循环当前节点后移;
        endwhile
        :将外循环当前节点后移;
    endwhile
stop
@enduml